// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/three/three-transformcontrols.d.ts
declare namespace THREE {
	class TransformControls extends Object3D {
		constructor(object:Camera, domElement?:HTMLElement);

		object: Object3D;

		update():void;
		detach(): void;
		attach(object: Object3D): void;
		getMode(): string;
		setMode(mode: string): void;
		setSnap(snap: any): void;
		setSize(size:number):void;
		setSpace(space:string):void;

	}
}
