#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR/../

./node_modules/leaf-require-cli/bin/leaf-require --force-overwrite -r /script -o ./src/require.json --set-version $RANDOM ./src/script
./node_modules/leaf-require-cli/bin/leaf-require --force-overwrite -r /test -o ./src/test/require.json --set-version $RANDOM ./src/test --main "test"
